let x , y ;
x=20;
y=30;
console.log('x and y are equal');
console.log(x===y);
console.log('x and y are *not* equal');
console.log(x!==y);
console.log('x is greater than y');
console.log(x>y);
console.log('x is less than or equal to y');
console.log(x<=y);
console.log(' y is greater than x');
console.log(y>x);
let z = 5;
let f , g ;
f=x*z;
g=z+y;
console.log('Multiply z and x, and check whether this result is greater than z added to y');
console.log(f>g);
let u, i;
u=x-z;
i=y/z;
console.log('Subtract z from x and check whether this result is less than y divided by z');
console.log(u<i);
console.log('z, x and y are equal');
console.log(x===y===z);
let xz , yz;
xz = x%z;
yz =y%z;
console.log('remainder of x divided by z and the remainder of y divided by z are equal');
console.log(xz===yz);
let zx, zy;
zx=x+z;
zy=y-z;
console.log('z added to x is greater than y minus z');
console.log(zx>zy);
console.log('z added to x is smaller than y minus z');
console.log(zx<zy);

console.log('');
console.log('');