const STR1="Sophie";
console.log(STR1);
let second=STR1[1];
console.log(second);
let sixth=STR1[5];
console.log(sixth);
let name = "Jamil";
const AGE=27;
const YEAR=2019;
let declare=`${name} is ${AGE} in ${YEAR}`;
console.log(declare);
let isMarried=false;
let question = name = isMarried? 'true':'false';
console.log(question);
const PROGRAMMINGLANGUAGE = 'JavaScript';
let isFun=true;
let fun=isFun?'javaScript is fun':'false';
console.log(fun);
console.log(PROGRAMMINGLANGUAGE[0]);
console.log(PROGRAMMINGLANGUAGE[4]);
console.log(PROGRAMMINGLANGUAGE.length);