let str1="Sophie";
console.log(str1);
let second=str1[1];
console.log(second);
let sixth=str1[5];
console.log(sixth);
let name = "Jamil";
let age=27;
let year=2019;
let declare=`${name} is ${age} in ${year}`;
console.log(declare);
let isMarried=false;
let question = name = isMarried? 'true':'false';
console.log(question);
let programmingLanguage = 'JavaScript';
let isFun=true;
let fun=isFun?'javaScript is fun':'false';
console.log(fun);
console.log(programmingLanguage[0]);
console.log(programmingLanguage[4]);
console.log(programmingLanguage.length);