console.log("1. Console log a line of text");
console.log("");
console.log("Oceanic Feeling");
console.log("");
console.log("2. Declare a variable and give your variable the value -This is the value-");
console.log("");
let firstVar = 'This is the value.'
console.log(firstVar);
console.log("");
console.log("3. Declare a variable called firstName and assign your first name to that variable. Do the same with your last name. Console log both variables.");
let firstName = 'Nicolo';
let lastName = 'Tommasi';
console.log("");
let myId = `My first and last Name: ${firstName} ${lastName}`;
console.log(myId);
console.log("");
console.log("4. Make a profile of someone's information. Store all the information in variables eg. name, city, job etc. (five variables total) Console log the variables.");
console.log("");
let someName = 'Braia Nino'; 
let someCity = 'Brera';
let someJob = 'Singer';
let someAge = '39';
let someMaritalstatus = 'Married';
let braiaNino = `Name: ${someName}, City: ${someCity}, Occupation ${someJob}, Age: ${someAge}, Marital Status: ${someMaritalstatus}`;
console.log(braiaNino);
console.log("");
console.log("5. Print a sentence using the profile variables above, adding text where necessary for sentence flow");
console.log("");
// console.log(someName, 'is a famous', someJob, 'born and raised in', someCity, '. He is now', someAge, 'and he is', someMaritalstatus, 'to a beautiful woman named Susy.');
// console.log("");
console.log(`${someName} is a famous ${someJob} born and raised in ${someCity}. He is now ${someAge} and he is ${someMaritalstatus} to a beautful woman named Susy.`);