let first = 'this is an exercise';
let second='in console logging';
let main = `${first} ${second}`;
console.log(main);
let val1="This is the value.";
console.log(val1);
let firstName, lastName;
firstName="Jamil";
lastName="alsulaiman";
let fullName=`${firstName} ${lastName}`;
console.log(fullName);
let hobby, music, job ,and;
hobby="my hobby is football";
music="my favorite music is nothing";
job="my job is a student";
and= "and";
let info = `${hobby} ${and} ${music} ${and} ${job}`;
console.log(hobby);
console.log(music);
console.log(job);
console.log(info);

