let introSentence = "hello, my name is Fran and I am";
let age = 25;
console.log(`${introSentence} ${age}`);
console.log('the + operator is not doing any thing cause i did not use it');
let myNumber=1005;
let myNUMBER=parseInt(myNumber,10);
console.log(myNUMBER);
let myNumber_2=10.05;
let myNUMBER_2=parseInt(myNumber_2,16);
console.log(myNUMBER_2);
let check = 30? 'even': 939? 'odd':40.9?'odd':'even';
console.log(check);