let x = 7;
let y = 5;
console.log(x - y);
console.log(y - x);
console.log(x * y);
console.log(x / y);
let z = 10;
let resultOne = x * y / z;
console.log(resultOne);
let a = 15;
let b = 9;
console.log(a / b);
let c = 20;
let resultTwo = a + b * c;
console.log(resultTwo);
a++;
b--;
let d = b - a;
console.log(d + c);
console.log(resultOne / resultTwo);