let x = 3;
console.log(x);
let y = 4;
console.log(y);
x + y;
console.log( x + y);
x - y;
console.log(x - y);
y - x;
console.log(y - x);
x * y;
console.log(x * y);
x / y;
console.log(x / y);
let z = 10;
console.log(z);
x * y / z;
console.log(x * y / z)
let resultOne = x * y / z;
console.log(resultOne);
let a = 15;
console.log(a);
let b = 9;
console.log(b);
a / b;
console.log(a / b);
let c = 20;
console.log(c);
a + b * c;
console.log(a + b * c);
let resultTwo = a + b * c;
console.log(resultTwo);
a++;
console.log(a++);
b--;
console.log(b--);
b - a;
console.log(b - a)
let d = b - a;
console.log(d);
d + c;
console.log(d+c);
console.log(resultOne % resultTwo);