let x = 3;
let y = 4;
x + y;
console.log(x + y);
x - y;
console.log(x - y);
y - x;
console.log(y - x);
x * y;
console.log(x * y);
x / y;
console.log(x / y);
let z = 10;
x * y / z;
let resultOne = x * y / z;
console.log(resultOne);
let a = 15;
let b = 9;
a / b;
console.log(a / b);
let c = 20;
a + b * c;
let resultTwo = a + b * c;
console.log(resultTwo);
a++;
b--;
b - a;
let d = b - a;
d + c;
console.log(resultOne % resultTwo);